name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . -t ${{ secrets.REGISTRY }}/${{ secrets.REPOSITORY }}:latest
          docker push ${{ secrets.REGISTRY }}/${{ secrets.REPOSITORY }}:latest
